# Generated by Django 3.2.7 on 2022-01-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_alter_console_description'),
        ('storefronts', '0003_alter_storefront_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('condition', models.CharField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/listing-images')),
                ('description', models.TextField(blank=True, null=True)),
                ('copies_available', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.game')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefronts.storefront')),
            ],
        ),
    ]
