# Generated by Django 3.2.7 on 2022-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
