# Generated by Django 3.2.7 on 2022-01-28 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_sku'),
        ('checkout', '0005_auto_20220128_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
            preserve_default=False,
        ),
    ]
