# Generated by Django 3.2.9 on 2021-12-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_game_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
