# Generated by Django 3.2.9 on 2021-12-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211206_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Publisher',
        ),
        migrations.RenameField(
            model_name='console',
            old_name='brand',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='brand',
            new_name='publisher',
        ),
    ]
