# Generated by Django 3.2.9 on 2021-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_game_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='image_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='image_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
