# Generated by Django 3.2.7 on 2022-01-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211210_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
