# Generated by Django 3.2.7 on 2022-01-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefronts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/storefront-images'),
        ),
    ]
