# Generated by Django 3.2.7 on 2022-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefronts', '0002_alter_storefront_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/storefront-images'),
        ),
    ]
